"""Generate the tattoo pen tip mesh.

URDF has no cone primitive, and the pen needs a point rather than a flat disc at
the end. This writes that cone as a binary STL, parametrically, so the shape is
reproducible rather than a binary blob someone has to trust.

The mesh is in millimetres to match the exported CAD meshes, which the
description scales by 0.01. It is a *visual* only: the collision geometry stays
the full cylinder, which is conservative and is what a collision check should
use. Nothing about `tattoo_tcp` moves - the cone ends exactly where the tip
already was.

    python3 docs/scripts/make_pen_tip.py
"""

import struct
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "src/tattotronix_description/meshes/visual/tattoo_pen_tip.stl"

RADIUS_MM = 3.0     # matches the pen cylinder
TAPER_MM = 8.0      # how much of the tip is cone
FACETS = 48         # enough that the silhouette reads as smooth at this size


def cone(radius, height, facets):
    """Triangles of a cone from z=0 (base, radius) to z=height (apex), plus its base."""
    th = np.linspace(0.0, 2.0 * np.pi, facets, endpoint=False)
    ring = np.column_stack([radius * np.cos(th), radius * np.sin(th),
                            np.zeros_like(th)])
    apex = np.array([0.0, 0.0, height])
    centre = np.zeros(3)
    tris = []
    for i in range(facets):
        a, b = ring[i], ring[(i + 1) % facets]
        tris.append((a, b, apex))        # side, wound so the normal points out
        tris.append((b, a, centre))      # base, wound the other way
    return tris


def write_stl(path, tris):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "wb") as f:
        f.write(b"tattotronix pen tip, generated by docs/scripts/make_pen_tip.py".ljust(80, b"\0"))
        f.write(struct.pack("<I", len(tris)))
        for a, b, c in tris:
            n = np.cross(b - a, c - a)
            ln = np.linalg.norm(n)
            n = n / ln if ln > 0 else np.zeros(3)
            f.write(struct.pack("<12fH", *n, *a, *b, *c, 0))


if __name__ == "__main__":
    tris = cone(RADIUS_MM, TAPER_MM, FACETS)
    write_stl(OUT, tris)
    print(f"wrote {OUT}")
    print(f"  {len(tris)} triangles, base radius {RADIUS_MM} mm, "
          f"height {TAPER_MM} mm, in millimetres")
